# Generated by Django 5.1.5 on 2025-01-31 15:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

def insert_initial_data(apps, schema_editor):
    #company
    Company = apps.get_model('api', 'Company')
    Company.objects.create(company_name='PMA', email  ='info@pma.com', mobile='00000355355')

    #Branch
    Branch = apps.get_model('api', 'Branch')
    Branch.objects.create( name  ='Main', company= 1 )

    Company = apps.get_model('api', 'Company')