# Generated by Django 5.1.5 on 2025-02-03 06:04

import cr.chores.chores
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias_id', models.CharField(default=cr.chores.chores.generate_unique_id, editable=False, max_length=10, unique=True)),
                ('company_name', models.TextField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile', models.TextField()),
                ('version', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias_id', models.CharField(default=cr.chores.chores.generate_unique_id, editable=False, max_length=10, unique=True)),
                ('name', models.TextField()),
                ('version', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.company')),
            ],
            options={
                'verbose_name': 'branch',
                'verbose_name_plural': 'branches',
                'db_table': 'branch',
            },
        ),
    ]
