# Generated by Django 5.1.5 on 2025-02-12 16:54

import cr.inve_lib.inve_lib
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_branch_created_at_remove_branch_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={},
        ),
        migrations.AlterField(
            model_name='branch',
            name='alias_id',
            field=models.SlugField(default=cr.inve_lib.inve_lib.generate_slugify_id, editable=False, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='company',
            name='alias_id',
            field=models.CharField(default=cr.inve_lib.inve_lib.generate_slugify_id, editable=False, max_length=10, unique=True),
        ),
        migrations.AlterModelTable(
            name='branch',
            table=None,
        ),
    ]
