# Generated by Django 5.1.5 on 2025-02-13 13:04

import cr.inve_lib.inve_lib
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_branch_options_alter_branch_alias_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='grace_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='branch',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CreditInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias_id', models.TextField(default=cr.inve_lib.inve_lib.generate_alias_id, editable=False, max_length=10, unique=True)),
                ('invoice_no', models.TextField()),
                ('transaction_date', models.DateField()),
                ('delivery_man', models.TextField(blank=True, null=True)),
                ('transaction_details', models.TextField(blank=True, null=True)),
                ('due_amount', models.DecimalField(decimal_places=4, max_digits=18)),
                ('payment_grace_days', models.IntegerField(default=0)),
                ('invoice_image', models.ImageField(null=True, upload_to='invoices/')),
                ('status', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.IntegerField(default=1)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.branch')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.customer')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Credit Invoice',
                'verbose_name_plural': 'Credit Invoices',
            },
        ),
    ]
