# Generated by Django 5.1.5 on 2025-02-14 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_customer_grace_days_alter_branch_updated_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='grace_days',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
