# Generated by Django 5.1.5 on 2025-02-16 09:19

import cr.inve_lib.inve_lib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_customer_grace_days'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'verbose_name': 'Branch', 'verbose_name_plural': 'Branches'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Customer', 'verbose_name_plural': 'Customers'},
        ),
        migrations.AlterField(
            model_name='creditinvoice',
            name='alias_id',
            field=models.SlugField(default=cr.inve_lib.inve_lib.generate_alias_id, editable=False, max_length=10, unique=True),
        ),
    ]
