# Generated by Django 5.1.5 on 2025-02-16 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_branch_options_alter_customer_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditinvoice',
            name='alias_id',
            field=models.TextField(default='0d031697bd', editable=False, max_length=10, unique=True),
        ),
    ]
