# Generated by Django 5.1.5 on 2025-02-20 11:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_creditinvoice_alias_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditinvoice',
            name='alias_id',
            field=models.TextField(default='d0b4eb7e2e', editable=False, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='creditinvoice',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ChequeStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias_id', models.TextField(default='8e4565bc17', editable=False, max_length=10, unique=True)),
                ('received_date', models.DateField()),
                ('cheque_image', models.ImageField(null=True, upload_to='cheque_images/')),
                ('cheque_date', models.DateField(blank=True, null=True)),
                ('cheque_amount', models.DecimalField(decimal_places=4, max_digits=18)),
                ('cheque_detail', models.TextField(default='')),
                ('cheque_status', models.IntegerField(choices=[(1, 'Received'), (2, 'Cheque Deposited'), (3, 'Honored'), (4, 'Dishonored'), (5, 'Canceled')], default=1)),
                ('Notes', models.TextField(default='')),
                ('isActive', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.IntegerField(default=1)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.branch')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.customer')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cheque Store',
                'verbose_name_plural': 'Cheque Stores',
                'db_table': 'cheque_store',
            },
        ),
        migrations.CreateModel(
            name='InvoiceChequeMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjusted_amount', models.DecimalField(decimal_places=4, max_digits=18)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.IntegerField(default=1)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.branch')),
                ('cheque_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_cheques', to='api.chequestore')),
                ('creditinvoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.creditinvoice')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Invoice Cheque Map',
                'verbose_name_plural': 'Invoice Cheque Maps',
                'db_table': 'invoice_cheque_map',
            },
        ),
    ]
