# Generated by Django 5.1.5 on 2025-02-20 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_creditinvoice_alias_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chequestore',
            name='alias_id',
            field=models.TextField(default='fa45bff399', editable=False, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='creditinvoice',
            name='alias_id',
            field=models.TextField(default='7131b91ff7', editable=False, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='alias_id',
            field=models.TextField(default='1a238cd119', editable=False, max_length=10, unique=True),
        ),
    ]
