# Generated by Django 5.1.5 on 2025-02-20 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_chequestore_alias_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chequestore',
            name='alias_id',
            field=models.TextField(default='d616968c53', editable=False, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='creditinvoice',
            name='alias_id',
            field=models.TextField(default='93fc010158', editable=False, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='alias_id',
            field=models.TextField(default='a163579660', editable=False, max_length=10, unique=True),
        ),
    ]
