# Generated by Django 5.1.5 on 2025-02-23 13:12

import cr.inve_lib.inve_lib
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_chequestore_alias_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='branch',
            field=models.ForeignKey( on_delete=django.db.models.deletion.PROTECT, to='api.branch'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chequestore',
            name='alias_id',
            field=models.TextField(default=cr.inve_lib.inve_lib.generate_slugify_id, editable=False, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='creditinvoice',
            name='alias_id',
            field=models.TextField(default=cr.inve_lib.inve_lib.generate_slugify_id, editable=False, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='alias_id',
            field=models.TextField(default='bb17e3c3ac', editable=False, max_length=10, unique=True),
        ),
    ]
