# Generated by Django 5.1.5 on 2025-02-23 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_customer_alias_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='alias_id',
            field=models.TextField(default='285bd3e6ba', editable=False, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='branch',
            field=models.ForeignKey( on_delete=django.db.models.deletion.PROTECT, to='api.branch'),
        ),
    ]
