# Generated by Django 5.1.5 on 2025-02-23 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_customer_alias_id_alter_customer_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='alias_id',
            field=models.TextField(default='64ae328fc7', editable=False, max_length=10, unique=True),
        ),
    ]
