# Generated by Django 5.1.5 on 2025-02-23 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_customer_alias_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='alias_id',
            field=models.TextField(default='5133502776', editable=False, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.branch'),
        ),
    ]
