# Generated by Django 5.1.5 on 2025-02-23 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_customer_alias_id_alter_customer_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='alias_id',
            field=models.TextField(default='0448b9c468', editable=False, max_length=10, unique=True),
        ),
    ]
