# Generated by Django 5.1.5 on 2025-02-23 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_customer_alias_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='alias_id',
            field=models.TextField(default='85f647b202', editable=False, max_length=10, unique=True),
        ),
    ]
