# Generated by Django 5.1.5 on 2025-02-23 20:09

import cr.inve_lib.inve_lib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_customer_alias_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='alias_id',
            field=models.TextField(default=cr.inve_lib.inve_lib.generate_slugify_id, editable=False, max_length=10, unique=True),
        ),
    ]
