# Generated by Django 5.1.5 on 2025-03-02 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_customerclaim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chequestore',
            name='cheque_status',
            field=models.IntegerField(choices=[(1, 'Received'), (2, 'Deposited'), (3, 'Honored'), (4, 'Bounced')], default=1),
        ),
    ]
